/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_archivepatcher_generator_bsdiff_wrapper_BsDiffNativePatchWriter */

#ifndef _Included_com_google_archivepatcher_generator_bsdiff_wrapper_BsDiffNativePatchWriter
#define _Included_com_google_archivepatcher_generator_bsdiff_wrapper_BsDiffNativePatchWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_archivepatcher_generator_bsdiff_wrapper_BsDiffNativePatchWriter
 * Method:    nativeGeneratePatchFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_archivepatcher_generator_bsdiff_wrapper_BsDiffNativePatchWriter_nativeGeneratePatchFile
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_google_archivepatcher_generator_bsdiff_wrapper_BsDiffNativePatchWriter
 * Method:    nativeGeneratePatchData
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_archivepatcher_generator_bsdiff_wrapper_BsDiffNativePatchWriter_nativeGeneratePatchData
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
